/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   resources_sprites_enemy.h                          :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: juperez <juperez@student.42.fr>            +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2025/04/21 10:15:47 by juperez           #+#    #+#             */
/*   Updated: 2025/04/24 05:56:51 by juperez          ###   ########.fr       */
/*                                                                            */
/* ************************************************************************** */

#ifndef RESOURCES_SPRITES_ENEMY_H
# define RESOURCES_SPRITES_ENEMY_H

// IDLE
# define EI1A1	"../resources/assets/sprites/enemy/idl_1/A1.xpm"
# define EI1A2	"../resources/assets/sprites/enemy/idl_1/A2.xpm"
# define EI1A3	"../resources/assets/sprites/enemy/idl_1/A3.xpm"
# define EI1A4	"../resources/assets/sprites/enemy/idl_1/A4.xpm"
# define EI1A5	"../resources/assets/sprites/enemy/idl_1/A5.xpm"
# define EI1A6	"../resources/assets/sprites/enemy/idl_1/A6.xpm"
# define EI1A7	"../resources/assets/sprites/enemy/idl_1/A7.xpm"
# define EI1A8	"../resources/assets/sprites/enemy/idl_1/A8.xpm"
# define EI1B1	"../resources/assets/sprites/enemy/idl_1/B1.xpm"
# define EI1B2	"../resources/assets/sprites/enemy/idl_1/B2.xpm"
# define EI1B3	"../resources/assets/sprites/enemy/idl_1/B3.xpm"
# define EI1B4	"../resources/assets/sprites/enemy/idl_1/B4.xpm"
# define EI1B5	"../resources/assets/sprites/enemy/idl_1/B5.xpm"
# define EI1B6	"../resources/assets/sprites/enemy/idl_1/B6.xpm"
# define EI1B7	"../resources/assets/sprites/enemy/idl_1/B7.xpm"
# define EI1B8	"../resources/assets/sprites/enemy/idl_1/B8.xpm"
# define EI1C1	"../resources/assets/sprites/enemy/idl_1/C1.xpm"
# define EI1C2	"../resources/assets/sprites/enemy/idl_1/C2.xpm"
# define EI1C3	"../resources/assets/sprites/enemy/idl_1/C3.xpm"
# define EI1C4	"../resources/assets/sprites/enemy/idl_1/C4.xpm"
# define EI1C5	"../resources/assets/sprites/enemy/idl_1/C5.xpm"
# define EI1C6	"../resources/assets/sprites/enemy/idl_1/C6.xpm"
# define EI1C7	"../resources/assets/sprites/enemy/idl_1/C7.xpm"
# define EI1C8	"../resources/assets/sprites/enemy/idl_1/C8.xpm"

// WALK
# define EW1A1	"../resources/assets/sprites/enemy/wlk_1/A1.xpm"
# define EW1A2	"../resources/assets/sprites/enemy/wlk_1/A2.xpm"
# define EW1A3	"../resources/assets/sprites/enemy/wlk_1/A3.xpm"
# define EW1A4	"../resources/assets/sprites/enemy/wlk_1/A4.xpm"
# define EW1A5	"../resources/assets/sprites/enemy/wlk_1/A5.xpm"
# define EW1A6	"../resources/assets/sprites/enemy/wlk_1/A6.xpm"
# define EW1A7	"../resources/assets/sprites/enemy/wlk_1/A7.xpm"
# define EW1A8	"../resources/assets/sprites/enemy/wlk_1/A8.xpm"
# define EW1B1	"../resources/assets/sprites/enemy/wlk_1/B1.xpm"
# define EW1B2	"../resources/assets/sprites/enemy/wlk_1/B2.xpm"
# define EW1B3	"../resources/assets/sprites/enemy/wlk_1/B3.xpm"
# define EW1B4	"../resources/assets/sprites/enemy/wlk_1/B4.xpm"
# define EW1B5	"../resources/assets/sprites/enemy/wlk_1/B5.xpm"
# define EW1B6	"../resources/assets/sprites/enemy/wlk_1/B6.xpm"
# define EW1B7	"../resources/assets/sprites/enemy/wlk_1/B7.xpm"
# define EW1B8	"../resources/assets/sprites/enemy/wlk_1/B8.xpm"
# define EW1C1	"../resources/assets/sprites/enemy/wlk_1/C1.xpm"
# define EW1C2	"../resources/assets/sprites/enemy/wlk_1/C2.xpm"
# define EW1C3	"../resources/assets/sprites/enemy/wlk_1/C3.xpm"
# define EW1C4	"../resources/assets/sprites/enemy/wlk_1/C4.xpm"
# define EW1C5	"../resources/assets/sprites/enemy/wlk_1/C5.xpm"
# define EW1C6	"../resources/assets/sprites/enemy/wlk_1/C6.xpm"
# define EW1C7	"../resources/assets/sprites/enemy/wlk_1/C7.xpm"
# define EW1C8	"../resources/assets/sprites/enemy/wlk_1/C8.xpm"
# define EW1D1	"../resources/assets/sprites/enemy/wlk_1/D1.xpm"
# define EW1D2	"../resources/assets/sprites/enemy/wlk_1/D2.xpm"
# define EW1D3	"../resources/assets/sprites/enemy/wlk_1/D3.xpm"
# define EW1D4	"../resources/assets/sprites/enemy/wlk_1/D4.xpm"
# define EW1D5	"../resources/assets/sprites/enemy/wlk_1/D5.xpm"
# define EW1D6	"../resources/assets/sprites/enemy/wlk_1/D6.xpm"
# define EW1D7	"../resources/assets/sprites/enemy/wlk_1/D7.xpm"
# define EW1D8	"../resources/assets/sprites/enemy/wlk_1/D8.xpm"

// ATTACK_1
# define EA1A1	"../resources/assets/sprites/enemy/atk_1/A1.xpm"
# define EA1A2	"../resources/assets/sprites/enemy/atk_1/A2.xpm"
# define EA1A3	"../resources/assets/sprites/enemy/atk_1/A3.xpm"
# define EA1A4	"../resources/assets/sprites/enemy/atk_1/A4.xpm"
# define EA1A5	"../resources/assets/sprites/enemy/atk_1/A5.xpm"
# define EA1A6	"../resources/assets/sprites/enemy/atk_1/A6.xpm"
# define EA1A7	"../resources/assets/sprites/enemy/atk_1/A7.xpm"
# define EA1A8	"../resources/assets/sprites/enemy/atk_1/A8.xpm"
# define EA1B1	"../resources/assets/sprites/enemy/atk_1/B1.xpm"
# define EA1B2	"../resources/assets/sprites/enemy/atk_1/B2.xpm"
# define EA1B3	"../resources/assets/sprites/enemy/atk_1/B3.xpm"
# define EA1B4	"../resources/assets/sprites/enemy/atk_1/B4.xpm"
# define EA1B5	"../resources/assets/sprites/enemy/atk_1/B5.xpm"
# define EA1B6	"../resources/assets/sprites/enemy/atk_1/B6.xpm"
# define EA1B7	"../resources/assets/sprites/enemy/atk_1/B7.xpm"
# define EA1B8	"../resources/assets/sprites/enemy/atk_1/B8.xpm"
# define EA1C1	"../resources/assets/sprites/enemy/atk_1/C1.xpm"
# define EA1C2	"../resources/assets/sprites/enemy/atk_1/C2.xpm"
# define EA1C3	"../resources/assets/sprites/enemy/atk_1/C3.xpm"
# define EA1C4	"../resources/assets/sprites/enemy/atk_1/C4.xpm"
# define EA1C5	"../resources/assets/sprites/enemy/atk_1/C5.xpm"
# define EA1C6	"../resources/assets/sprites/enemy/atk_1/C6.xpm"
# define EA1C7	"../resources/assets/sprites/enemy/atk_1/C7.xpm"
# define EA1C8	"../resources/assets/sprites/enemy/atk_1/C8.xpm"
# define EA1D1	"../resources/assets/sprites/enemy/atk_1/D1.xpm"
# define EA1D2	"../resources/assets/sprites/enemy/atk_1/D2.xpm"
# define EA1D3	"../resources/assets/sprites/enemy/atk_1/D3.xpm"
# define EA1D4	"../resources/assets/sprites/enemy/atk_1/D4.xpm"
# define EA1D5	"../resources/assets/sprites/enemy/atk_1/D5.xpm"
# define EA1D6	"../resources/assets/sprites/enemy/atk_1/D6.xpm"
# define EA1D7	"../resources/assets/sprites/enemy/atk_1/D7.xpm"
# define EA1D8	"../resources/assets/sprites/enemy/atk_1/D8.xpm"

// ATTACK_2
# define EA2A1	"../resources/assets/sprites/enemy/atk_2/A1.xpm"
# define EA2A2	"../resources/assets/sprites/enemy/atk_2/A2.xpm"
# define EA2A3	"../resources/assets/sprites/enemy/atk_2/A3.xpm"
# define EA2A4	"../resources/assets/sprites/enemy/atk_2/A4.xpm"
# define EA2A5	"../resources/assets/sprites/enemy/atk_2/A5.xpm"
# define EA2A6	"../resources/assets/sprites/enemy/atk_2/A6.xpm"
# define EA2A7	"../resources/assets/sprites/enemy/atk_2/A7.xpm"
# define EA2A8	"../resources/assets/sprites/enemy/atk_2/A8.xpm"
# define EA2B1	"../resources/assets/sprites/enemy/atk_2/B1.xpm"
# define EA2B2	"../resources/assets/sprites/enemy/atk_2/B2.xpm"
# define EA2B3	"../resources/assets/sprites/enemy/atk_2/B3.xpm"
# define EA2B4	"../resources/assets/sprites/enemy/atk_2/B4.xpm"
# define EA2B5	"../resources/assets/sprites/enemy/atk_2/B5.xpm"
# define EA2B6	"../resources/assets/sprites/enemy/atk_2/B6.xpm"
# define EA2B7	"../resources/assets/sprites/enemy/atk_2/B7.xpm"
# define EA2B8	"../resources/assets/sprites/enemy/atk_2/B8.xpm"
# define EA2C1	"../resources/assets/sprites/enemy/atk_2/C1.xpm"
# define EA2C2	"../resources/assets/sprites/enemy/atk_2/C2.xpm"
# define EA2C3	"../resources/assets/sprites/enemy/atk_2/C3.xpm"
# define EA2C4	"../resources/assets/sprites/enemy/atk_2/C4.xpm"
# define EA2C5	"../resources/assets/sprites/enemy/atk_2/C5.xpm"
# define EA2C6	"../resources/assets/sprites/enemy/atk_2/C6.xpm"
# define EA2C7	"../resources/assets/sprites/enemy/atk_2/C7.xpm"
# define EA2C8	"../resources/assets/sprites/enemy/atk_2/C8.xpm"
# define EA2D1	"../resources/assets/sprites/enemy/atk_2/D1.xpm"
# define EA2D2	"../resources/assets/sprites/enemy/atk_2/D2.xpm"
# define EA2D3	"../resources/assets/sprites/enemy/atk_2/D3.xpm"
# define EA2D4	"../resources/assets/sprites/enemy/atk_2/D4.xpm"
# define EA2D5	"../resources/assets/sprites/enemy/atk_2/D5.xpm"
# define EA2D6	"../resources/assets/sprites/enemy/atk_2/D6.xpm"
# define EA2D7	"../resources/assets/sprites/enemy/atk_2/D7.xpm"
# define EA2D8	"../resources/assets/sprites/enemy/atk_2/D8.xpm"

// DIE_1
# define ED1A1	"../resources/assets/sprites/enemy/die_1/A1.xpm"
# define ED1B1	"../resources/assets/sprites/enemy/die_1/B1.xpm"
# define ED1C1	"../resources/assets/sprites/enemy/die_1/C1.xpm"
# define ED1D1	"../resources/assets/sprites/enemy/die_1/D1.xpm"
# define ED1E1	"../resources/assets/sprites/enemy/die_1/E1.xpm"
# define ED1F1	"../resources/assets/sprites/enemy/die_1/F1.xpm"

// DIE_2
# define ED2A1	"../resources/assets/sprites/enemy/die_2/A1.xpm"
# define ED2B1	"../resources/assets/sprites/enemy/die_2/B1.xpm"
# define ED2C1	"../resources/assets/sprites/enemy/die_2/C1.xpm"
# define ED2D1	"../resources/assets/sprites/enemy/die_2/D1.xpm"
# define ED2E1	"../resources/assets/sprites/enemy/die_2/E1.xpm"
# define ED2F1	"../resources/assets/sprites/enemy/die_2/F1.xpm"

#endif
